# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35ticpg236-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Electricity/Desktop/TankLast/Tank.cache/wt [current_project]
set_property parent.project_path C:/Users/Electricity/Desktop/TankLast/Tank.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions disable [current_project]
read_verilog -library xil_defaultlib -sv {
  C:/Users/Electricity/Desktop/TankLast/Tank.srcs/sources_1/new/objectCol.sv
  C:/Users/Electricity/Desktop/TankLast/Tank.srcs/sources_1/new/forward.sv
  C:/Users/Electricity/Desktop/TankLast/Tank.srcs/sources_1/new/VGA.sv
  C:/Users/Electricity/Desktop/TankLast/Tank.srcs/sources_1/new/counterGenerator.sv
  C:/Users/Electricity/Desktop/TankLast/Tank.srcs/sources_1/new/clkdiv.sv
  C:/Users/Electricity/Desktop/TankLast/Tank.srcs/sources_1/new/tank.sv
  C:/Users/Electricity/Desktop/TankLast/Tank.srcs/sources_1/new/tankGame.sv
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Electricity/Desktop/TankLast/Tank.srcs/constrs_1/new/game.xdc
set_property used_in_implementation false [get_files C:/Users/Electricity/Desktop/TankLast/Tank.srcs/constrs_1/new/game.xdc]


synth_design -top tankGame -part xc7a35ticpg236-1L


write_checkpoint -force -noxdef tankGame.dcp

catch { report_utilization -file tankGame_utilization_synth.rpt -pb tankGame_utilization_synth.pb }
